[package]
name = "ptex"
version = "0.0.1"
edition = "2018"
authors = ["David Aguilar <davvid@gmail.com>"]
description = "High-level Ptex bindings over ptex-sys"
license = "Apache-2.0"

[dependencies]
anyhow = "1.0"
ptex-sys = {path = "../ptex-sys", version = "2.4.1"}
thiserror = "1.0"
