[package]
name = "ptex-rs"
version = "0.1.1"
edition = "2018"
authors = ["David Aguilar <davvid@gmail.com>"]
description = "High-level Ptex bindings over ptex-sys"
license = "Apache-2.0"

[dependencies]
anyhow = "1.0"
ptex-sys = "2.4.1"
# ptex-sys = {path = "../ptex-sys"}
thiserror = "1.0"
